### ISSUE TITLE
Generate json with device and image dimensions

### ISSUE THREAD

**Issue by scurrilus-funke** [onderceylan/pwa-asset-generator#248]
Hi @onderceylan,

first of all thanks for your nice work. It saves a lot of time to create the pwa artwork via script.
In the following I would like to briefly describe an idea.

You have the option to create a manifest.json and an index.html. Since I am currently working on a react project, I have written a component in this context that generates the respective <link> elements based on a JSON data set, which are also included in your index.html. I created this JSON file myself based on the index.html which cost me a little time.

Furthermore, this cannot be updated particularly well. Especially if pwa-asset-generator contains an update with new device types.

My feature suggestion: You can generate a JSON based on index.html, which contains all device types and image sizes that were created with pwa-asset-generator.

**Example:**
JSON file so called PwaList.json
```JSON
[
    {
        "imageWidth": "2048",
        "imageHeight": "2732",
        "deviceWidth": "1024",
        "deviceHeight": "1366",
        "pixelRatio": "2"
    },
    ...
]
```

React component
```javascript
import PwaList from './PwaList.json';

const orientation = ['portrait', 'landscape'];

PwaList.map(item => {
                return orientation.map(oItem => {
                    const imageName = `${oItem === 'portrait' ? item.imageWidth : item.imageHeight}-${
                        oItem === 'portrait' ? item.imageHeight : item.imageWidth
                    }`;
                    return (
                        <link
                            key={imageName}
                            rel="apple-touch-startup-image"
                            href={`${rootPath}/apple-splash-${imageName}.png`}
                            media={`(device-width: ${item.deviceWidth}px) and (device-height: ${item.deviceHeight}px) and (-webkit-device-pixel-ratio: ${item.pixelRatio}) and (orientation: ${oItem})`}
                        />
                    );
                });
            })
```

The advantage with this solution. It would not matter to the site how many new devices or image pre-formats are added. The component handles what is in the JSON. With this I can easily create new art works and would not have to worry about updating index.html. Furthermore, a framework like next.js does not have index.html. There are many advantages to the integration as a component itself.

I hope you understand what I want to do. And I look forward to an answer.
best Peter

**Comment by onderceylan** [comment]
Hi @scurrilus-funke, thanks for using PWA Asset Generator (PAG) and sharing your feedback! I understood your proposition. PAG already uses such file as a source of truth for splash screen and meta html generation. 

It's being generated over PAG's scraper: https://github.com/onderceylan/pwa-asset-generator/runs/629521252?check_suite_focus=true#step:7:21

PAG uses this file on the distributed npm package as a config file and it's already available when you install PAG as a dependency in your project.

Install PAG as a dependency;
`npm i -D pwa-asset-generator`

Import the json file from this path;
`const pagConfig = require('pwa-asset-generator/dist/config/apple-fallback-data.json')` or 
`import * as pagConfig from 'pwa-asset-generator/dist/config/apple-fallback-data.json'`.

Since you ask this, I will expose this json file as a public data along with generateImages method of PAG so that people with similar intention can access it over the module.

After this change, it will be as easy as importing it via
`import { appleDeviceSpecsForLaunchImages } from 'pwa-asset-generator'` statement. Would that meet with your expectations?

**Comment by scurrilus-funke** [comment]
Hi @onderceylan ,

this would be greeat. This is exactly what i am searching for. Thank you.

best Peter
