### ISSUE TITLE
Use PNG as a default format for manifest icons

### ISSUE THREAD

**Issue by marharyta** [onderceylan/pwa-asset-generator#337]
**Is your feature request related to a problem? Please describe.**
As specified at the URL: [https://web.dev/splash-screen/?utm_source=lighthouse&utm_medium=devtools](https://web.dev/splash-screen/?utm_source=lighthouse&utm_medium=devtools) it looks like the Splash scree requires the icon imported into manifest to be a PNG, yet the util generates .JPG

**Describe the solution you'd like**
An opportunity to specify image format, or change in default behaviour, possible step-by-step question process. 

**Describe alternatives you've considered**
Just renaming seems to be fine, but it took me some time to figure out why Lighthouse is complaining about the existing 512 image.

**Additional context**
<img width="717" alt="Screenshot 2020-07-07 at 17 09 06" src="https://user-images.githubusercontent.com/7344718/86793875-93679580-c074-11ea-89f8-f5339215191c.png">

**Comment by onderceylan** [comment]
Hey @marharyta, thanks for using pwa-asset-generator and providing your feedback.

What's referred in Lighthouse is the icons defined in manifest file. Once you have png icons generated, that warning should go away. And, it's currently possible to specify icons in png format via pwa-asset-generator using the `--type` param.

An example use would be;

```
$ pwa-asset-generator logo.svg ./assets --icon-only --type png
```

The splash screen images are particularly generated for Apple platform and it's intentionally set with JPG type by default, due to the large file size of PNG files.

Step-by-step question driven input building sounds interesting. This might be a good addition to the lib in the future. Thanks!

**Comment by marharyta** [comment]
Thanks for the fast reply @onderceylan

**Comment by onderceylan** [comment]
I'm converting this issue to a bug as saving PNG was the earlier functionality of the CLI and when switched to JPG by default, manifest icons are also started to be saved as JPG files instead of PNG files. 

I'm going to introduce a hybrid default for the types, creating an exception for Web App Manifest icons.
