### ISSUE TITLE
Transparent background does not work

### ISSUE THREAD

**Issue by elmeerr** [onderceylan/pwa-asset-generator#68]
**Describe the bug**
The docs says that transparent background is default but this is not happening

**To Reproduce**
1. Execute cli command `npx pwa-asset-generator https://icon-library.net/images/img_566996.png`
2. Open generated images
3. See error

**Expected behavior**
Images with transparent background.

**System (please complete the following information):**
 - OS: windows 10
 - node version 12.13.0
 - npm version 6.12.0
 - cli version 2.1.1

**Screenshots**
Webstorm show if the background is transparent (which is not in this case)
![image](https://user-images.githubusercontent.com/4071037/68409687-d3921380-0187-11ea-96b3-f03cabc32b54.png)

**Comment by onderceylan** [comment]
Hi @elmeerr, thanks for the feedback. Although default background color is transparent, there's another option that you need to use which impacts this scenario: **opaque**.

You need to run your command with **--opaque false** option in order to get the transparency;
`npx pwa-asset-generator https://icon-library.net/images/img_566996.png --opaque false`

I understand this might be confusing but it's necessary to use for the background css values with alpha channels.

**Comment by onderceylan** [comment]
I'm updating the docs to clarify this btw, thanks for the heads up!

**Comment by elmeerr** [comment]
@onderceylan Thanks for clarifying this!
